### ISSUE TITLE
Create local tests for more PHP versions

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#241]
To run local tests I'm using 
https://hub.docker.com/r/futureys/phpunit-wordpress-plugin/
which by default uses PHP 7.4.8.

Some users are still on PHP 7.2 that has reached EOL. 
PHP 7.3 allows trailing commas in function calls (https://wiki.php.net/rfc/trailing-comma-function-calls) and because I used that and forgot about 7.2 and earlier the plugin broke for some users (https://wordpress.org/support/topic/latest-version-2-41-1-is-crashing-the-site/).

So by adding a local way to also test the plugin on older versions of PHP would be useful.

## Todo

- [x] Copy and modify `Dockerfile` to use PHP version 7.2.
- [x] Add image to Docker Hub
- [x] Use image in tests, as variable so we can change image easily

**Comment by bonny** [comment]
Running `npm test` now run tests on

- WordPress 5.6.2 with PHP 7.2
- WordPress 5.6.2 with PHP 7.4.15
- WordPress 5.2 with PHP 5.6

So for example trailing commas in functions call will be caught.

**Comment by bonny** [comment]
I needed to create some new docker images for this btw, they can be found here:
https://hub.docker.com/repository/docker/eskapism/phpunit-wordpress-plugin
