### ISSUE TITLE
Check that post status is updated correctly

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#343]
From [support forum](https://wordpress.org/support/topic/more-obvious-log-of-post_status-changes/)

- Publishing/de-publishing on the usual edit post page: fully covered by Simple History
- Schedule publishing in the future on the usual edit post page: scheduled status seems to be covered by Simple History, but when the publishing actually happens isn’t
- Change status through Quick Edit on the listing page: Simple History appears to cover everything but the status change
- Change status through Bulk actions > Edit on the listing page: Simple History appears to cover everything but the status change

## Investigation

Plugin does not take into consideration that future posts get status `future` and that a cron job changes that to `publish`. Interesting hooks and functions: hook `publish_future_post`, `_future_post_hook`, `check_and_publish_future_post()`.

## Todo

- [x] Bulk edit: status not shown in diff message
- [x] Bulk edit: post thumbnail always shown as added
- [x] Bulk edit: user change is not shown
- [x] Post edit: removal of post thumb just show as empty before image
- [x] Post edit: user change shown but missing translation?
- [ ] Post: switching status in the future is not detected
