### ISSUE TITLE
wp cli enhancements

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#352]
- [ ] bonny/Simple-History-Plus#3
- [x] bonny/Simple-History-Plus#2

- [x] bonny/Simple-History-Plus#1
- [x] Add note to readme that wp cli actually exists
