### ISSUE TITLE
Enhance the plugin preview and the empty state after install/activate

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#418]
The Live Preview buttons is enabled now, 
but the view you get to looks a bit "sad".

![CleanShot 2024-01-12 at 08 33 57@2x](https://github.com/bonny/WordPress-Simple-History/assets/221570/9c559a58-d865-43d9-8962-6e1730a6bee0)

## Todo

- [x] #317 
- [x] Fix 'Activated plugin "{plugin_name}"'
- [ ] Make it more graphical. Add "examples" of post diffs, image uploads, etc.?
- [ ] On wordpress.org we could run some "setup code" that fakes failed login attempts, makes edits, and so on.

**Comment by bonny** [comment]
A little bit better:

![CleanShot 2024-01-21 at 16 56 44@2x](https://github.com/bonny/WordPress-Simple-History/assets/221570/1860dc70-2a2c-4b39-a7a9-3193807c553d)
