### ISSUE TITLE
MySQL/MariaDB `MAX_JOIN_SIZE` errors

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#435]
Reported here in the forums and privately on Slack:

- https://wordpress.org/support/topic/the-logs-arent-shown/

> WordPress database error: 
> [The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay]

The query is the usual query used to get the log overview.

This probably happens on shared hosts that have more strict db settigs.

So far users with this error have been running MariaDB.

Some random links about this:

- https://stackoverflow.com/questions/943423/mysql-the-select-would-examine-more-than-max-join-size-rows
- https://stackoverflow.com/questions/966815/mysql-max-join-size-errors
- https://stackoverflow.com/questions/950465/mysql-sql-big-selects
- https://gist.github.com/jessepearson/8483962539463f1890edad68852034bd
- https://support.tigertech.net/mysql-max-join-size

Database info from one user with this problem:
![image](https://github.com/bonny/WordPress-Simple-History/assets/221570/c3d125e7-749e-49de-ad33-5804c9840962)
![image](https://github.com/bonny/WordPress-Simple-History/assets/221570/9189d296-9338-449f-a642-e9186e0746fa)

Debug screenshot from another user:
![image](https://github.com/bonny/WordPress-Simple-History/assets/221570/41f55a38-7621-4996-b058-d2d53bbfbcd4)

A third user reports their db-sizes:
> DB tables are OK (80 + 1100 rows).

---

![image](https://github.com/bonny/WordPress-Simple-History/assets/221570/dbd5ecde-6598-4b56-aab9-b4ef95be025a)

> If I use SET max_join_size=18446744073709551615; before query, it works. So there is a problem in the local “268435456” value – too low.

---

## Todo

- [ ] Add more info to the debug page, ie. `MAX_JOIN_SIZE` settings value.
- [ ] Detect this error when querying db and return more useful error.
- [ ] Reproduce locally
- [ ] Come up with fix: rewrite sql query, modify tables to add indexes, change query for lower end hosts (maybe remove occasions support)

**Comment by bonny** [comment]
Hopefully fixed in [version 4.14.0](https://wordpress.org/plugins/simple-history/#developers)

**Comment by NekoJonez** [comment]
So far, so fixed. Been testing it on my websites and it's working flawlessly.
