### ISSUE TITLE
Add message about giving a review 🌟 

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#485]
When plugin has been installed for longer than nn days and more than nn messages have been logged, then display a "reminder" message for users to give a nice review.

Many plugins show this message directly after install which feel to intrusive. Waiting for a user to use the plugin for a while and apparently keeping the plugin hopefully leads to more users willing to give a review.

## Tasks

- [x] Display a message only to users with capability `manage_options`
- [x] Let user hide the message
- [x] Display message close to the log
- [x] Display message only on pages with simple history (don't pollute admin)

**Comment by bonny** [comment]
Rank Math SEO does it this way:
![Image](https://github.com/user-attachments/assets/aa6d2c87-0a3b-47a8-a5f3-e0023cb6009a)

**Comment by bonny** [comment]
Limit Login Attempts

![Image](https://github.com/user-attachments/assets/2be717fb-ef14-4171-a63b-c3cb03d956dc)

**Comment by bonny** [comment]
Temp login plugin

![Image](https://github.com/user-attachments/assets/ca14ebb9-1048-4f39-9e70-0019cd87c7f2)

**Comment by bonny** [comment]
Ok done.

Only show on pages that belongs to Simple History (including the dashboard, because the widget is there).

Is only shown once and only if many events has been shown, so it does not show right away for new users.

Looks like this:

![Image](https://github.com/user-attachments/assets/6ef283c9-b8b6-4500-8b63-226cf7453c6c)
