### ISSUE TITLE
Move Simple History to top level admin menu

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#486]
There is both a feed and a settings page and debug page etc. so there is time to give it it's own menu in the left menu area.

## Todo

- [x] When clicking menu below dashboard append query string like "?simple_history_redirected_from_dashboard_menu".
- [x] Redirect from Settings › Simple History to new setting page below main menu item.
- [x] Add Simple History logo-header to all child menu pages (make one re-usable template).
- [x] Make settings tabs work again (missing query string args).
- [x] Settings page does not need main settings tab, only child tabs.
- [x] Show message that menu page has moved when above query string is detected.
- [x] Remove "Event details tests (dev)" that is shown for users with history debug enabled.
- [x] Remove "Styles example (dev)" that is shown for users with history debug enabled.
- [x] "Settings saved" message disappeared!
- [x] ["Message control"](https://simple-history.com/add-ons/premium/#message-control) stopped working (enabling and disabling loggers does not work).

**Comment by bonny** [comment]
Saw this in a video, other similar plugins for sure does use the main menu :)

![CleanShot 2024-12-27 at 10 46 13@2x](https://github.com/user-attachments/assets/999327b8-3c1e-43e8-9919-0e02ce9590e1)

**Comment by bonny** [comment]
Todays progress. I really like it! Feels so much better.

![image](https://github.com/user-attachments/assets/b7fcab96-f008-4052-984c-4406d83db177)

**Comment by bonny** [comment]
A message is now shown for users that visit the log via "Dashboard » Simple History" or "Settings » Simple History".

![Image](https://github.com/user-attachments/assets/2a3e4517-db9e-4b31-ad56-de7f4da5dfcf)
